@startuml

package Data <<Folder>>{
class Player
class Board
class Turn
class Option
class TypePlayer

Board *-- Turn
Turn *-- Player
Player *-- TypePlayer
Turn o-- Option

Board : - id_board int
Board : - max_rounds int
Board : - round_counter int


Option : - id_option int
Option : - name string

Turn : - id_turn int
Turn : - id_player int
Turn : - throw option

Player : - id_player int
Player : - name String
Player : - id_playerType int

TypePlayer : id_typePlayer int
TypePlayer : name String

}



@enduml